name: "ci"
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”¥ checkout code
        uses: actions/checkout@v2
      - name: âš¡ install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: ğŸ—ƒï¸ cache Rust
        uses: Swatinem/rust-cache@v1
#      - name: âš¡ install webkit2gtk (ubuntu only)
#        if: matrix.platform == 'ubuntu-latest'
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y webkit2gtk-4.0 libgtksourceview-3.0-dev
      - name: âœ… run rust tests
        run: cargo test
      - name: âœ… run rust doc
        run: cargo doc
      - name: ğŸšš move docs to gh-pages
        run: cp -r target/doc/ public/
      - name: âœ… run rust lint
        continue-on-error: true
        run: cargo clippy
      - name: ğŸ“¦ deploy public to gh-pages
        uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true